# Generated by Django 5.1.2 on 2024-11-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_membershipplan_price_alter_trainer_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='SelectMembershipplan',
            new_name='SelectMembershipPlane',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Salary',
            new_name='Qualification',
        ),
    ]
