# Generated by Django 5.1.2 on 2024-11-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_selectmembershipplan_enrollment_selectmembershipplane_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='Qualification',
            field=models.CharField(max_length=400),
        ),
    ]
