# Generated by Django 5.1.2 on 2024-11-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_enrollment_duedate_enrollment_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='DueDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
    ]
