# Generated by Django 5.1.2 on 2024-12-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_membershipplan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Reference',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='paymentStatus',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='timeStamp',
        ),
    ]
