# Generated by Django 5.1.2 on 2024-12-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_remove_enrollment_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='DueDate',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='PaymentStatus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Timestamp',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
    ]
