# Generated by Django 5.1.2 on 2024-12-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
